### ISSUE TITLE
Broken Help Command

### ISSUE THREAD

**Issue by l3CY** [K-4U/k4lib#1]
Tested in a clean instance using only k4lib

Version: k4lib-1.7.10-0.1.35-universal.jar
Forge: Build 1.7.10-10.13.3.1408-1.7.10 

Performing the /help command causes the following error: http://pastebin.com/Smkrq8ra

**Comment by DarkTechnician** [comment]
Theres actually a mod out there that fixes this error. Its known as HelpFixer.

**Comment by l3CY** [comment]
I actually tried using that before posting this issue.  Sadly, it didn't work with k4lib.

**Comment by Aedda** [comment]
HelpFixer will be unable to fix this as this issue is outside its power. HelpFixer prevents commands from corrupting the help system however in the case of k4lib it appears the bug is in the actual k4lib command. That bug being calling a method that does not always exist.

I've traced the problem to k4lib/lib/Functions.java line 55:
MinecraftServer.getServer().getConfigurationManager().func_152603_m().func_152690_d()

func_152690_d() is not defined in the cases k4lib causes help to fail. I do not know enough about the parent method to devise a theory as to why. It however can probably be solved by checking for the method prior to calling it.

Copy of the stack trace when using /help with HelpFixer 1.0.7 installed. https://gist.github.com/Aedda/9c7062624ed317d23aa1 as you can see comparing to the stack trace in op that this happens after HelpFixer does it's thing.

Thankfully this should be a simple thing to fix.
